version: '3'

services:
  nginx:
    container_name: server_nginx
    restart: 'no'
    build: ./nginx/tests
    ports:
      - 3000:80
    networks:
      - running-tests

networks:
  running-tests:
