version: '3'

services:
  ngnix:
    container_name: server
    restart: always
    build: ./nginx
    mem_limit: '2G'
    tty: false
    stdin_open: false
    volumes:
      - builder_nginx_vol:/www/data
    depends_on:
      - builder
    ports:
      - 80:80

  builder:
    env_file:
      - .env.prod
    container_name: front-build
    tty: false
    stdin_open: false
    mem_limit: '2G'
    build: '.'
    volumes:
      - builder_nginx_vol:/app/build

volumes:
  builder_nginx_vol:
