version: '3'

services:
  ngnix:
    container_name: server
    restart: always
    build: ./nginx
    mem_limit: '2G'
    tty: false
    stdin_open: false
    volumes:
      - builder_nginx_vol:/www/data
    ports:
      - 80:80

volumes:
  builder_nginx_vol:
