version: '3'

services:
  nginx:
    container_name: server_nginx
    restart: 'no'
    build: ./nginx/tests
    ports:
      - 3000:80
    volumes:
      - /out:/www/data/out
    networks:
      - running-tests

volumes:
  builder_nginx_vol:
networks:
  running-tests:
