version: '3'

services:
  ngnix:
    container_name: server
    restart: on-failure
    build: ./nginx/tests
    volumes:
      - builder_nginx_vol_tests:/www/data
    depends_on:
      - builder
    ports:
      - 3000:80

  builder:
    env_file:
      - .env.local
    container_name: front-build
    build: '.'
    volumes:
      - builder_nginx_vol_tests:/app/build

volumes:
  builder_nginx_vol_tests:
