version: '3'

services:
  ngnix:
    container_name: server
    restart: always
    build: ./nginx
    volumes:
      - builder_nginx_vol:/www/data
    depends_on:
      - builder
    ports:
      - 3000:80

  builder:
    env_file:
      - .env.prod
    container_name: front-build
    build: '.'
    volumes:
      - builder_nginx_vol:/app/build

volumes:
  builder_nginx_vol:
