version: '3'

services:
  nginx:
    container_name: server_nginx
    restart: 'no'
    build:
      context: .
      dockerfile: ./nginx/tests/Dockerfile
    ports:
      - 3000:80
    networks:
      - running-tests

volumes:
  builder_nginx_vol:
networks:
  running-tests:
