name: Test, Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "${{ secrets.ENV_LOCAL_FILE }}" > .env.prod
      - name: Clean
        run: sudo docker compose down
      - name: Build
        run: sudo docker compose build
      - name: Run
        run: sudo docker compose up -d
